### ISSUE TITLE
blender 3.6 install error

### ISSUE THREAD

**Issue by AlexNorth365** [lightfield-analysis/blender-addon#15]
Dear there.

My system is apple mac m1,my blender is 3.6. after installing and enabling it, I have the following error, looking forward to your reply!

Traceback (most recent call last):
  File "/Applications/Blender3.6.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/cdy/Library/Application Support/Blender/3.6/scripts/addons/blender-addon-master/__init__.py", line 61, in <module>
    class LFPropertyGroup(bpy.types.PropertyGroup):
  File "/Users/cdy/Library/Application Support/Blender/3.6/scripts/addons/blender-addon-master/__init__.py", line 176, in LFPropertyGroup
    default=updates.get_default_target_directory(),
  File "/Users/cdy/Library/Application Support/Blender/3.6/scripts/addons/blender-addon-master/updates.py", line 105, in get_default_target_directory
    path = os.path.join(bpy.context.user_preferences.filepaths.temporary_directory, 'lightfield')
AttributeError: '_RestrictContext' object has no attribute 'user_preferences'

**Comment by Max1Power** [comment]
change _user_preferences_ to _preferences_ in the file /scripts/addons/blender-addon-master/updates.py

`path = os.path.join(bpy.context.preferences.filepaths.temporary_directory, 'lightfield')`

**Comment by PisCes318** [comment]
Can blender3.6 be used?
